# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'neflix_clone_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Kingfisher', '~> 6.0'




  # Pods for neflix_clone_app

  target 'neflix_clone_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'neflix_clone_appUITests' do
    # Pods for testing
  end

end
